name: OCRTranslate
options:
  bundleIdPrefix: com.limaoswag
  deploymentTarget:
    iOS: "15.0"
  developmentLanguage: zh-Hans

settings:
  base:
    ALWAYS_SEARCH_USER_PATHS: false
    SWIFT_VERSION: "5.0"
    TARGETED_DEVICE_FAMILY: "1,2"
    IPHONEOS_DEPLOYMENT_TARGET: "15.0"
    CODE_SIGNING_ALLOWED: "NO"
    CODE_SIGNING_REQUIRED: "NO"
    CODE_SIGN_IDENTITY: ""
    DEVELOPMENT_TEAM: ""
    MARKETING_VERSION: "1.0.1"
    CURRENT_PROJECT_VERSION: "2"

targets:
  OCRTranslate:
    type: application
    platform: iOS
    sources:
      - path: OCRTranslate/App
      - path: OCRTranslate/Views
      - path: OCRTranslate/Resources
      - path: Shared
    info:
      path: OCRTranslate/Info.plist
      properties:
        CFBundleDisplayName: "OCR屏幕翻译"
    entitlements:
      path: OCRTranslate/OCRTranslate.entitlements
    settings:
      base:
        PRODUCT_NAME: "$(TARGET_NAME)"
        PRODUCT_BUNDLE_IDENTIFIER: com.limaoswag.ocrtranslate
        CODE_SIGN_STYLE: Manual
        CODE_SIGNING_ALLOWED: "NO"
        CODE_SIGNING_REQUIRED: "NO"
        CODE_SIGN_IDENTITY: ""
        DEVELOPMENT_TEAM: ""
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        MARKETING_VERSION: "1.0.1"
        CURRENT_PROJECT_VERSION: "2"
    dependencies:
      - target: ScreenTranslator
        embed: true

  ScreenTranslator:
    type: app-extension
    platform: iOS
    sources:
      - path: ScreenTranslator
      - path: Shared
    info:
      path: ScreenTranslator/Info.plist
      properties:
        CFBundleShortVersionString: "1.0.1"
        CFBundleVersion: "2"
        NSExtension:
          NSExtensionAttributes:
            RPBroadcastProcessMode: "RPBroadcastProcessModeSampleBuffer"
          NSExtensionPointIdentifier: "com.apple.broadcast-services-upload"
          NSExtensionPrincipalClass: "ScreenTranslator.SampleHandler"
    entitlements:
      path: ScreenTranslator/ScreenTranslator.entitlements
    settings:
      base:
        PRODUCT_NAME: "$(TARGET_NAME)"
        PRODUCT_BUNDLE_IDENTIFIER: com.limaoswag.ocrtranslate.ScreenTranslator
        CODE_SIGN_STYLE: Manual
        CODE_SIGNING_ALLOWED: "NO"
        CODE_SIGNING_REQUIRED: "NO"
        CODE_SIGN_IDENTITY: ""
        DEVELOPMENT_TEAM: ""
        MARKETING_VERSION: "1.0.1"
        CURRENT_PROJECT_VERSION: "2"
