name: OCRTranslate
options:
  bundleIdPrefix: com.limaoswag
  deploymentTarget:
    iOS: "15.0"
  developmentLanguage: zh-Hans

settings:
  base:
    ALWAYS_SEARCH_USER_PATHS: false
    SWIFT_VERSION: "5.0"
    TARGETED_DEVICE_FAMILY: "1,2"
    IPHONEOS_DEPLOYMENT_TARGET: "15.0"

targets:
  OCRTranslate:
    type: application
    platform: iOS
    sources:
      - path: OCRTranslate/App
      - path: OCRTranslate/Views
      - path: OCRTranslate/Resources
      - path: Shared
    info:
      path: OCRTranslate/Info.plist
    entitlements:
      path: OCRTranslate/OCRTranslate.entitlements
    settings:
      base:
        PRODUCT_NAME: "$(TARGET_NAME)"
        PRODUCT_BUNDLE_IDENTIFIER: com.limaoswag.ocrtranslate
        CODE_SIGN_STYLE: Automatic
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
    dependencies:
      - target: ScreenTranslator
        embed: true

  ScreenTranslator:
    type: app-extension
    platform: iOS
    sources:
      - path: ScreenTranslator
      - path: Shared
    info:
      path: ScreenTranslator/Info.plist
    entitlements:
      path: ScreenTranslator/ScreenTranslator.entitlements
    settings:
      base:
        PRODUCT_NAME: "$(TARGET_NAME)"
        PRODUCT_BUNDLE_IDENTIFIER: com.limaoswag.ocrtranslate.ScreenTranslator
        CODE_SIGN_STYLE: Automatic
